### ISSUE TITLE
Error: Flash Download failed  -  "Cortex-M0"

### ISSUE THREAD

**Issue by gunaone** [tulingBerg/SantaWhoop#1]
please help..

**Comment by tulingBerg** [comment]
Can you be more specific where you encountered the Problem?

**Comment by gunaone** [comment]
i try do flash download from keil, but i get **Error: Flash Download failed - "Cortex-M0"**
![Untitled](https://user-images.githubusercontent.com/12540556/69871715-1a39e000-12e6-11ea-932d-a2193ec517ff.png)

**Comment by tulingBerg** [comment]
I flash with "STM32 ST-Link Utility" directly. And you need to follow the
instructions in the description especially if you flash for the first time!

Am Fr., 29. Nov. 2019 um 14:23 Uhr schrieb guna_on3 Hatibie <
notifications@github.com>:

**Comment by gunaone** [comment]
Aha, that right... I try flash drom st link utility and that's work...
Thanks u so much...

**Comment by gunaone** [comment]
@tulingBerg i use flysky fsi6 multiprotocol, but i can't switch to level mode, is always on acro mode..
where is my mistake?
