### ISSUE TITLE
level mode doesn't work in switch

### ISSUE THREAD

**Issue by gunaone** [tulingBerg/SantaWhoop#2]
please help,,, thanks

**Comment by tulingBerg** [comment]
"To change to acro mode use gesture with the rigt stick when the quad is disarmed: left-left-down"
As described in the introduction :)
If you need further help, let me know!

**Comment by gunaone** [comment]
I was trying..
But ist didn't work. 
Still in acro mode

**Comment by tulingBerg** [comment]
Are you using the original TX?

guna_on3 Hatibie <notifications@github.com> schrieb am Do., 5. Dez. 2019,
14:47:

**Comment by gunaone** [comment]
i using flysky fs i6 with multyprotocol
edit:
i flashed with "tulingBerg_silverware_multiModule.hex"

and i try to with in zip file.

**Comment by tulingBerg** [comment]
You need to assign the following channels:
Ch1 - Ail
Ch2 - Ele
Ch3 - Thr
Ch4 - Rud
Ch5 - arm/disarm (100/0)
Ch6 - level/acro (-100/100)
Ch10 - sound module on/off (-100/100)

Hope that helps, let me know.

guna_on3 Hatibie <notifications@github.com> schrieb am Fr., 6. Dez. 2019,
03:28:

**Comment by gunaone** [comment]
in my flysky fs i6,
Ch1 - Ail --->ok
Ch2 - Ele --->ok
Ch3 - Thr --->ok
Ch4 - Rud --->ok
Ch5 - led on/off
Ch6 - arm/disarm
Ch10 - not working

**Comment by tulingBerg** [comment]
I will compile a version for you.
What features do you need on what channel?

guna_on3 Hatibie <notifications@github.com> schrieb am Fr., 6. Dez. 2019,
12:36:

**Comment by gunaone** [comment]
Nothing, I love your settings...
Just make it work level and acro mode 
🙏

**Comment by tulingBerg** [comment]
Added a firmware for 6 channels only. So you will not be able to switch on your music :-/
ch5 is arm/disarm
ch6 is level/acro
Let me know if it works...

**Comment by tulingBerg** [comment]
https://github.com/tulingBerg/SantaWhoop/blob/master/tulingBerg_silverware_multiModule_6CH.hex

**Comment by gunaone** [comment]
thanks u so much, 
nice, insyaallah i will try this night..

**Comment by gunaone** [comment]
hi @tulingBerg 
its doesnt work anyway,

and bytheway, i change transmiter to DEVO its work well,
but the led not working,
like your set =
Ch1 - Ail    ok
Ch2 - Ele   ok 
Ch3 - Thr   ok 
Ch4 - Rud  ok
Ch5 - arm/disarm (100/0)    ok
Ch6 - level/acro (-100/100)  ok
Ch10 - sound module on/off (-100/100)     non

thanks @tulingBerg , great job

**Comment by gunaone** [comment]
btw , what the difference with e011 and other fc.?
jjrch67 cant to be flash with NFE of Silferware
